server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8888
  servlet:
    context-path: /test
    
mybatis:
  mapper-locations:
  - classpath:mapper1/*.xml
  - classpath:mapper2/*.xml
  configuration:
#    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
    cache-enabled: true
    
spring:
  jackson:
    serialization:
      indent-output: true

  mvc:
    throw-exception-if-no-handler-found: true
#    static-path-pattern: /static/**
  resources:
    add-mappings: true
          
service:
  database: test
  upload-dir: E:\upload
  c3p0:
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/${service.database}
    driverClass: com.mysql.jdbc.Driver
    user: root
    password: root
    minPoolSize: 20
    maxPoolSize: 30