server:
  port: 8003
  servlet:
    context-path: /test
    
mybatis:
  mapper-locations:
  - classpath:mapper1/*.xml
  - classpath:mapper2/*.xml
  configuration:
#    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
    cache-enabled: true
    
spring:
  jackson:
    serialization:
      indent-output: true
  servlet:
    multipart:
      location: E:\upload
netty:
  server: 
    name: ${spring.application.name}
    port: 7003
    zookeeper: 172.16.4.247:2181, 172.16.4.244:2181
      
  
service:
  database: test
  upload-dir: E:\upload
  c3p0:
    jdbcUrl: jdbc:mysql://172.16.4.247:3306/${service.database}
    driverClass: com.mysql.jdbc.Driver
    user: root
    password: root
    minPoolSize: 20
    maxPoolSize: 30