server:
  port: 8888
  servlet:
    context-path: /test
    
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml

  configuration:
#    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
    cache-enabled: true
    
spring:
  jackson:
    serialization:
      indent-output: true

      
service:
  database: test
  upload-dir: E:\upload
  c3p0:
    jdbcUrl: jdbc:mysql://192.168.3.241:3306/${service.database}?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    driverClass: com.mysql.jdbc.Driver
    user: root
    password: root
    minPoolSize: 5
    maxPoolSize: 20